#!/usr/bin/env node
/**
 * docs/wiki/*.md から「使い方アシスタント（オリゼくん）」用の知識ベースを生成する。
 *
 * - 各 wiki ファイルの「## 概要」セクションを抽出（次の見出しまで）
 * - 開発者向け（API/SDK/Architecture/MCP/Deployment/Operations）は除外
 * - 生成結果を apps/worker/src/routes/help-knowledge.generated.ts に書き出す
 *
 * 実行: node apps/worker/scripts/build-help-kb.mjs
 *       （ビルド前に手動実行、wiki更新時に再実行してコミット）
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../..');
const WIKI_DIR = path.join(ROOT, 'docs/wiki');
const OUT_FILE = path.join(__dirname, '../src/routes/help-knowledge.generated.ts');

// 開発者向け／知識ベースに含めない wiki ファイル
const EXCLUDE = new Set([
  '19-SDK-Reference.md',
  '20-API-Reference.md',
  '21-Deployment.md',
  '22-Operations.md',
  '23-Claude-Code-Integration.md',
  '24-MCP-Server.md',
  'Architecture.md',
  'Configuration.md',
  'Home.md', // 重複しやすいので除外
]);

/**
 * Markdown 本文から最初の「## 概要」セクションを抽出
 * @param {string} md
 * @returns {string} 抽出した概要テキスト（無ければ空文字）
 */
function extractOverview(md) {
  const lines = md.split('\n');
  const out = [];
  let inOverview = false;
  for (const line of lines) {
    if (/^##\s+概要\s*$/.test(line)) {
      inOverview = true;
      continue;
    }
    if (inOverview) {
      // 次の ## 見出しが来たら終了
      if (/^##\s+/.test(line)) break;
      out.push(line);
    }
  }
  return out.join('\n').trim();
}

/**
 * ファイル名からタイトル相当を取り出す
 * 例: "16-Chat-and-AutoReply.md" → "Chat and AutoReply"
 */
function deriveTitle(filename) {
  return filename
    .replace(/\.md$/, '')
    .replace(/^\d+-/, '')
    .replace(/-/g, ' ');
}

const files = fs
  .readdirSync(WIKI_DIR)
  .filter((f) => f.endsWith('.md') && !EXCLUDE.has(f))
  .sort();

const sections = [];
for (const f of files) {
  const md = fs.readFileSync(path.join(WIKI_DIR, f), 'utf8');
  // 最初の見出し (#) からタイトル取得（無ければファイル名から）
  const titleMatch = md.match(/^#\s+(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : deriveTitle(f);

  const overview = extractOverview(md);
  if (!overview) continue;

  sections.push({ file: f, title, overview });
}

// TS 定数として書き出す
const banner = `// ⚠ AUTO-GENERATED by apps/worker/scripts/build-help-kb.mjs
// docs/wiki/*.md から「## 概要」セクションを抽出した知識ベース。
// 直接編集しない。wiki 更新後に再生成してコミットする：
//   node apps/worker/scripts/build-help-kb.mjs
`;

const body =
  'export const WIKI_KNOWLEDGE = `\n' +
  sections
    .map(
      (s) =>
        `## ${s.title}\n` +
        `（出典: docs/wiki/${s.file}）\n\n` +
        s.overview
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\\`')
          .replace(/\$\{/g, '\\${') +
        '\n',
    )
    .join('\n---\n\n') +
  '\n`;\n';

fs.writeFileSync(OUT_FILE, banner + '\n' + body, 'utf8');
console.log(`✅ Generated: ${OUT_FILE}`);
console.log(`   Sections: ${sections.length}`);
console.log(`   Size: ${(body.length / 1024).toFixed(1)} KB`);
